version: '4.20'

services:
  server:
    container_name: api-card-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
    depends_on:
      - database

  database:
    container_name: api-card-database
    image: postgres:13.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
